const MAX_TITLE_LENGTH = 500;
const MIN_TITLE_LENGTH = 1;

const MAX_COUNTRY_LENGTH = 100;
const MIN_COUNTRY_LENGTH = 2;

const MAX_DIRECTOR_LENGTH = 100;
const MIN_DIRECTOR_LENGTH = 2;

const MAX_YEAR = new Date().getFullYear();
const MIN_YEAR = 1888;

export {
  MAX_TITLE_LENGTH,
  MIN_TITLE_LENGTH,
  MAX_COUNTRY_LENGTH,
  MIN_COUNTRY_LENGTH,
  MAX_DIRECTOR_LENGTH,
  MIN_DIRECTOR_LENGTH,
  MAX_YEAR,
  MIN_YEAR
};
